### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by debeetle** [open-eats/OpenEats#161]
It seems like that there's no supporting with Apple silicon.

**Comment by sepulzera** [comment]
This is probably due to the very old node version that the [dockerfile is still using](https://github.com/open-eats/openeats-web/blob/master/Dockerfile#L1).

You could try to bump the version to [something more recent](https://hub.docker.com/r/mhart/alpine-node/), like 14.17.3 or even 16.4.2. But chances are high that something will break, thus you probably want to try an older (still more recent) version first.

**Comment by derrobin154** [comment]
@sepulzera Hey, have the error on my Raspberry too, can you maybe explain to me how exactly I do it?

**Comment by sepulzera** [comment]
@derrobin154 If you really want to run openeats with docker on your raspberry pi, then you will have to build the docker images yourself, to bump the versions. In your local project, open the dockerfile that I linked above, and change the version number for node. I do not guarantee that it will work though. Such high bumps in version numbers will most likely brake other dependencies.

Your better option would be to take a look at OwnRecipes: https://github.com/ownrecipes/OwnRecipes
Disclaimer: I am the owner of OwnRecipes.

OwnRecipes is a fork of openeats, but up to date. It does look a bit different though.
I also wrote some lines about [running it on a Raspberry Pi](https://github.com/ownrecipes/OwnRecipes/blob/master/docs/Running_the_App_Tricks.md/#single-board-computer), as I do.
