### ISSUE TITLE
Ported to Django 2.x and Python 3.x

### ISSUE THREAD

**Issue by trancen** [open-eats/OpenEats#41]
Spent a few hours the past 2 evenings porting a copy of OE to Django 2.x and Python 3.x. Seems to working well. I used a none docker version from https://github.com/DeEgge/openeats 
Took a lot of googling to figure out some stuff, but everything I click on or add seems to work .

**Comment by RyanNoelk** [comment]
Im not really sure what this issue is about. OpenEats already runs on Django 2.x and Python 3.6. There is also already a issue on porting OpenEats to run outside of Docker. 

If you have code that you think would help get OpenEats to run outside of docker then please open a pull request or take your questions here: https://github.com/open-eats/OpenEats/issues/31

-Ryan
