### ISSUE TITLE
Units glued to numbers get lost without warning

### ISSUE THREAD

**Issue by renatolond** [open-eats/OpenEats#51]
I noticed that if I add units glued to the numbers of an ingredients (for instance `1g of salt`) the unit is dropped silently and the recipe is saved without the unit (in the example `1 of salt`)
I would expect that this either saved the unit or raised a validation error.
This is specially common in recipes written in portuguese.

**Comment by RyanNoelk** [comment]
Not sure why the unit is dropping off. I split the string on spaces and then try and figure out how to group the parts. The expected behavior is that if the first string isn't a number, the whole string gets saved as is. Then when you changed the servings on a recipe, that ingredient doesn't change. The full logic is found [here](https://github.com/open-eats/openeats-web/blob/4e0f53d86108254eac7b88d60b6c07c7c9b7bd8f/modules/recipe_form/utilts/parseIngredient.js#L46) 

I will look into the case you mentioned above.

**Comment by RyanNoelk** [comment]
This should be fixed now. check the latest master and reopen if it is still not working as expected.
