### ISSUE TITLE
Issues with HTTPS

### ISSUE THREAD

**Issue by iinux101** [open-eats/OpenEats#74]
I think I ALMOST have it, right now my firewall is disabled on my host, I know I am so close to getting SSL working, if you go to my host right now nginx is showing the green lock and the correct SSL, but i am getting a 502 Bad Gateway. Any help would be greatly appreciated.
My docker-prod.override.yml : 
```
version: '2.3'
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always
  api:
    restart: always
  web:
    restart: on-failure
  db:
    restart: always
```
My env_prod.list :
```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=PASSWORD

# Django config
API_URL=0.0.0.0:80
API_PORT=80
DJANGO_SECRET_KEY=KEY
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=www.domain.com
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:80
NODE_PORT=80
ALLOWED_HOST=www.domain.com
NODE_API_URL=https://www.domain.com
```

And my default.conf from /etc/nginx/conf.d : 
```
upstream api {
  ip_hash;
  server api:443;
}
server {    
    listen 443 ssl;

    root /config/www;    index index.html index.htm index.php;

    server_name domain.com www.domain.com;

    ssl_certificate      /letsencrypt/domain.com/fullchain1.pem;
    ssl_certificate_key  /letsencrypt/domain.com/privkey1.pem;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    client_max_body_size 0;

    # pass requests for dynamic content
      location / {
          proxy_set_header        Host $host;
          #proxy_set_header        X-Real-IP $remote_addr;
          #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header      X-Forwarded-Proto https;
          #proxy_ssl_verify     off;
          proxy_pass http://IP:80;
      }

    location /api/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://IP:80/api/;
    }

    location /static/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://IP:80/static/;
    }

    location /admin/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://IP:80/admin/;
    }

    location /static-files/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://IP:80/static-files/;
    }

    location /site-media/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://IP:80/site-media/;
    }
```

**Comment by RyanNoelk** [comment]
OpenEats comes with a dockerized Nginx server that will handle all the traffic redirects for you. Your `docker-prod.opverride.yml` file will tell nginx on what port to serve. So lets say you have the follow override file:
```
version: '2.3'
services:
  nginx:
    ports:
      - "12345:80"
    restart: always
  api:
    restart: always
  web:
    restart: on-failure
  db:
    restart: always
```

This means your OpenEats instance can be accessed via `localhost:12345`. This is great if you only ever want to access OpenEats over http, but you probably want to be able to access OpenEats over https. In order to do this is need another nginx/apache server that redirects all traffic from the internet to OpenEats. This nginx/apache server with terminate the SSL connection and forward the traffic to OpenEats.

It looks like you are using Nginx so I would go about this in three steps.
1. Change OpenEats port to something random (4000-20000)
2. Get your server's nginx server to serve OpenEats via http:
 - https://github.com/open-eats/OpenEats/blob/master/docs/Creating_a_proxy_server_for_docker.md
 - https://github.com/open-eats/OpenEats/blob/master/docs/samples/sample_nginx_proxy
3. Get your server's nginx server to serve OpenEats via https:
 - https://letsencrypt.org/getting-started/

I'm going to close this as serving the App from HTTPS is a bit out of scope. There are alot of tools out there that do this and even more server setups that it makes debugging this stuff hard.

Feel free to post questions here if you have them.

Good luck :)

**Comment by iinux101** [comment]
Thank you so much! I understand it now!

**Comment by iinux101** [comment]
Again, thanks a ton! Got it all up and running, was quite quick and easy once i grasped that the 2nd nginx instance was not the same as the docker container.

**Comment by iinux101** [comment]
Having an issue with /admin running g the following in my nginx conf :

location /admin/ {
        proxy_set_header        Host $host;
        #proxy_set_header        X-Real-IP $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        #proxy_ssl_verify       off;
        proxy_pass http://localhost:8000/admin/;
    }

With the above, I'm getting the 404 error, but if I use the IP and just HTTP instead of the url and HTTPS it works.

**Comment by mbryantms** [comment]
I too am getting an issue with my Admin page to load. Specifically, I am running the docker containers unmodified with appropriate settings. I can access OpenEats through https://food.tld.com with no issues. (Http redirects to https.) This is due to an nginx server routing traffic from the internet to the docker containers running it locally. However, https://food.tld.com/admin comes up with a 404 error which redirects to the NotFound page and the lovely ClipArt. I'm trying to play with the settings to get both the Djano admin section and the front end fed by API to work but having no luck. The nginx I'm serving just looks like this:

        location / {
                proxy_pass http://127.0.0.1:7000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
        }

Thoughts?

**Comment by RyanNoelk** [comment]
Looks like there is any issue with the Admin page not coming up. Will take a look at the server config and try and fix the issue in the next few days.

**Comment by RyanNoelk** [comment]
Just took a quick look and the issue has to do with the js service worker. it's caching he page and sending all requests to the UI.

If you open a private/incognito window and try to go to the admin page (my.domian.com/admin) without going to the UI first (my.domian.com) it will work.

**Comment by RyanNoelk** [comment]
I have fixed the issue with the admin panel. You should now be able to go there via the UI link
